workflows:
  ios-workflow:
    name: Build iOS

    environment:
      flutter: latest    # use latest stable
      xcode: latest

    scripts:
      - name: Run pre-build automation for podspecs
        script: |
          echo "Running pre-build script to update podspecs"
          chmod +x update_podspecs.sh
          ./update_podspecs.sh

      - name: Clean and install CocoaPods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..

      - name: Show Flutter version
        script: flutter --version

      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS Simulator (no codesign)
        script: flutter build ios --simulator --no-codesign

    artifacts:
      - build/ios/iphonesimulator/Runner.app
