workflows:
  ios-workflow:
    name: Build iOS
    environment:
      flutter: "3.16.0"
      xcode: latest
      vars:
        XCODE_PROJECT: "ios/Runner.xcodeproj"
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Clean project
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Validate Podfile presence
        script: |
          if [ ! -f ios/Podfile ]; then
            echo "No Podfile found, generating..."
            cd ios
            pod init
            cd ..
          else
            echo "✅ Podfile already exists."
          fi

      - name: Patch podspec license paths (prevent CocoaPods lint issues)
        script: |
          echo "Fixing podspec license paths..."
          find ios -name "*.podspec" -exec sed -i '' 's|:file => *[\"'\'']\.\./LICENSE[\"'\'']|:file => File.expand_path("../../LICENSE", __FILE__)|g' {} +

      - name: CocoaPods setup
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS for simulator (no codesign)
        script: flutter build ios --simulator --no-codesign

    artifacts:
      - build/ios/iphonesimulator/*.app
