workflows:
  ios-workflow:
    name: Build iOS
    environment:
      flutter: "3.19.0"        # use latest stable
      xcode: latest
      vars:
        XCODE_PROJECT: "ios/Runner.xcodeproj"
        XCODE_SCHEME: "Runner"

    scripts:
      # ── sanity check ────────────────────────────────
      - name: Show Flutter version
        script: flutter --version

      # ── project cleanup & deps ──────────────────────
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Ensure Podfile exists (platform iOS 13.0)
        script: |
          if [ ! -f ios/Podfile ]; then
            cd ios
            pod init
            sed -i '' '1s/^/platform :ios, '\''13.0'\''\n/' Podfile
            cd ..
          fi

      - name: Clean and install CocoaPods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
          cd ..

      # (optional) run your custom Podspec update script
      - name: Run pre‑build automation for podspecs
        script: |
          if [ -f update_podspecs.sh ]; then
            chmod +x update_podspecs.sh
            ./update_podspecs.sh
          fi

      # ── build ───────────────────────────────────────
      - name: Build iOS (no codesign)
        script: flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
