workflows:
  ios-workflow:
    name: Build iOS
    environment:
      flutter: "3.16.0"
      xcode: latest
    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Flutter pub get
        script: flutter pub get

      - name: Generate iOS build settings
        script: flutter build ios --simulator --no-codesign || true

      - name: Ensure Podfile exists
        script: |
          if [ ! -f ios/Podfile ]; then
            cd ios
            pod init
            sed -i '' '1s/^/platform :ios, '\''13.0'\''\n/' Podfile
            cd ..
          fi

      - name: Install CocoaPods
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS for simulator (no codesign)
        script: flutter build ios --simulator --no-codesign

    artifacts:
      - build/ios/iphonesimulator/*.app
