workflows:
  ios_simulator_build:
    name: Build iOS Simulator App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS simulator bundle
        script: flutter build ios --simulator --no-codesign

      - name: Zip the simulator app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner-sim.zip Runner.app
          cd -

    artifacts:
      - build/ios/iphonesimulator/Runner-sim.zip
    publishing:
      webhook-disabled: true
