name: find_pt_app
description: A new Flutter project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

include: package:lint/analysis_options.yaml

dependencies:
  flutter:
    sdk: flutter

  # core libs
  csv: ^6.0.0
  stylish_bottom_bar: ^1.1.0
  flutter_typeahead: ^5.2.0
  geolocator: ^14.0.0
  logger: ^2.5.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_app_check: ^0.3.2+5
  firebase_crashlytics: ^4.3.5
  cloud_functions: ^5.5.0

  # Stripe
  flutter_stripe: ^11.4.0

  # State management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1

  # Misc utilities
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  multi_select_flutter: ^4.1.3
  flutter_rating_bar: ^4.0.0
  intl: ^0.20.2
  url_launcher: ^6.2.5
  async: ^2.11.0
  fake_async: ^1.3.1
  freezed_annotation: ^2.4.4
  leak_tracker: ^10.0.0
  material_color_utilities: ^0.11.1
  app_links: ^6.4.0
  http: ^1.3.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.9.0
  flutter_email_sender: ^7.0.0
  flutter_dotenv: ^5.2.1
  extended_image: ^10.0.1
  image_editor: ^1.3.0
  image_editor_common: ^1.1.0
  image_cropper: ^9.1.0
  crop: ^0.5.5
  crop_image: ^1.0.16
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lint: ^2.4.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher_round.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/Fitly2.png"
  adaptive_icon_background: "#F3B342"
  web:
    generate: false
    image_path: "assets/ic_launcher_foreground.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/ic_launcher_foreground.png"
    icon_size: 48
  macos:
    generate: false
    image_path: "assets/ic_launcher_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.png
    - assets/Suburbs.json
    - assets/Fitly.png
    - assets/Fitly2.png
    - assets/fonts/Montserrat-Regular.ttf
    - assets/fonts/Montserrat-Bold.ttf
    - .env
    - assets/background.png
    - assets/1024.png

dependency_overrides:
  vm_service: 14.3.1
  material_color_utilities: ^0.11.1
  http: ^0.13.6
  flutter_secure_storage: ^9.2.4
