// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcgmNbMN1zkz-obl-9acGAEyihas3UI5Q',
    appId: '1:794098237480:web:6a10a0db29827ec395f51d',
    messagingSenderId: '794098237480',
    projectId: 'findptapp',
    authDomain: 'findptapp.firebaseapp.com',
    storageBucket: 'findptapp.firebasestorage.app',
    measurementId: 'G-7FB76NM3QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zll-HAAqxTQKK2Hqpu_dmiNfN-ZIZWs',
    appId: '1:794098237480:android:29084c1b1b031d0395f51d',
    messagingSenderId: '794098237480',
    projectId: 'findptapp',
    storageBucket: 'findptapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkpwELogJcoYFPqCDalBjIXBdMiH730s',
    appId: '1:794098237480:ios:05ac7fbae2fcbe5d95f51d',
    messagingSenderId: '794098237480',
    projectId: 'findptapp',
    storageBucket: 'findptapp.firebasestorage.app',
    iosBundleId: 'com.example.findPtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcgmNbMN1zkz-obl-9acGAEyihas3UI5Q',
    appId: '1:794098237480:web:d4be60cb0f10602595f51d',
    messagingSenderId: '794098237480',
    projectId: 'findptapp',
    authDomain: 'findptapp.firebaseapp.com',
    storageBucket: 'findptapp.firebasestorage.app',
    measurementId: 'G-0WXYS66B65',
  );
}
