# ios/Podfile
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Locate Flutter root so CI containers (Codemagic) can load podhelper
flutter_root = ENV['FLUTTER_ROOT'] ||
               File.expand_path('../..', __dir__) + '/flutter'
require File.expand_path(
  File.join('packages', 'flutter_tools', 'bin', 'podhelper'),
  flutter_root
)

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Standard Flutter pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
