include: package:flutter_lints/flutter_lints.yaml

analyzer:
  exclude:
    # Ignore generated files
    - '**/*.g.dart'
    - 'lib/src/generated/*.dart'
    - ios/**/example/**'
      
linter:
  rules:
    - public_member_api_docs