name: Build iOS Simulator App

on:
  push:
    branches:
      - ios-version
  workflow_dispatch:

jobs:
  build-ios-simulator:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dart & Flutter deps
        run: flutter pub get

      - name: Prepare CocoaPods
        working-directory: ios
        run: |
          pod repo update
          pod install --repo-update

      - name: Build iOS for Simulator
        run: flutter build ios --simulator --no-codesign

      - name: Zip the Simulator App
        run: |
          cd build/ios/iphonesimulator
          zip -r Runner-sim.zip Runner.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-simulator-app
          path: build/ios/iphonesimulator/Runner-sim.zip
